name: New Version From Issue
on:
  issues:
    types: ["opened", "reopened"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          env
          version=$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.body' | tail -n 1)
          echo "NEW_VERSION=${version}" >> $GITHUB_ENV
      - run: |
          echo ${NEW_VERSION}
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            let body = context.payload.issue.body
            if (body.startsWith('### Devlake New Version')) {
              let lines = body.split('\\n')
              let versionText = lines[lines.length-1]
              console.log(lines)
              console.log(versionText)
            }
