name: New Version From Issue
on:
  issues:
    types: ["opened", "reopened"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          env
          version=$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.body' | tail -n 1)
          echo "NEW_VERSION=${version}" >> $GITHUB_ENV
      - uses: actions/github-script@v6
        with:
          script: |
            const { NEW_VERSION } = process.env
            console.log(NEW_VERSION)
